### ISSUE TITLE
Looking to contribute to enhance KeyRing Program 

### ISSUE THREAD

**Issue by Hrushi20** [buffalojoec/keyring-program#4]
Hey! Are there any issue or enhancements I can contribute to improve the [keyring-program](https://github.com/buffalojoec/keyring-program).

**Comment by buffalojoec** [comment]
@Hrushi20 thanks for asking, but at this time it's not being actively developed! Until we see a need for this as an encryption companion for wallets, it's really just a reference example.

I have a few other repositories that are in active development that might be worth checking out. I will need to add some issues, but dropping a comment like you did above in any of those repos will let me know which ones you're interested in!

- [Mollusk](https://github.com/buffalojoec/mollusk)
- [PayTube](https://github.com/buffalojoec/paytube)
- [GraphQL Wallet](https://github.com/buffalojoec/graphql-wallet)
